### ISSUE TITLE
Bug: Does not work when setting SwaggerUIOptions

### ISSUE THREAD

**Issue by Scal-Human** [teociaps/SwaggerUI.Themes#14] opened 2024-07-01 15:58 UTC
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Project Version

0.5.0.0

### .NET Version

net8.0

### What happened?

Does nothing when defining SwaggerUIOptions along with the style

### Steps to reproduce

`
app.UseSwaggerUI(Style.DeepSea, (SwaggerUIOptions options) => { options.DisplayOperationId(); });
`

### Expected behavior

Changes the theme.

### Additional Information

Works when removing the SwaggerUIOptions.
`
app.UseSwaggerUI(Style.DeepSea);
`

**Comment by teociaps** [comment] 2024-07-01 18:00
Hi @Scal-Human,

I tried to reproduce the issue you're experiencing, but it works for me using the following code:
`app.UseSwaggerUI(Style.DeepSea, (SwaggerUIOptions options) => { options.DisplayOperationId(); });`

Do you see the loaded styles in your browser sources?
Are there any errors printed in your browser console?
Have you cleared your browser cache?

**Comment by Scal-Human** [comment] 2024-07-02 09:54
Hello,
Thank you for your concern.
No, I do not see any error, neither on the console, nor is the browser.
The style is simply ignored on both Windows and Linux (Docker container).
FYI: using the options was a test I removed anyway.
Thanks for your job, by the way ;-)
Scal

**Comment by teociaps** [comment] 2024-07-02 20:16
Oh, okay. I will investigate further.
For now, I close this issue because I can't reproduce it, and it doesn't seem to be a bug.
Thank you!

**Closed by teociaps** 2024-07-02 20:16 UTC
Labels: enhancement

**Comment by Scal-Human** [comment] 2024-07-04 16:25
Thank you Tarek.
In the meantime, I had to change the order of the middlewares I am using in my tests (trying to find common ground for all future servers), and with those changes, I added back a SwaggerUIOptions to have a standard openapi.json name instead of swagger.json and it now works.

``` c#
app.UseSwaggerUI(Style.Dark, (SwaggerUIOptions options) => {
    options.SwaggerEndpoint("v1/openapi.json", "Version 1");
    options.RoutePrefix = "api";
});
```

Unfortunately, I do not have anymore the exact code that was not working (but it was really simple).
What I suggest is for you not to investigate for now, and will come back to you if I can reproduce the case that was not working.

Thank you for your time,
Scal

**Comment by oasaleh** [comment] 2024-08-11 03:49
Well, here's the error. It's not being recognized.

![image](https://github.com/user-attachments/assets/abbda3bc-04bd-4a90-a568-07ddd185381b)


Here's the code,
```c#
        app.UseSwagger();
        app.UseSwaggerUI(
            ModernStyle.Dark,
            c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "PodiumApi v1");
                c.RoutePrefix = string.Empty; // this changes the default path
                c.EnableTryItOutByDefault();
                c.DocExpansion(DocExpansion.None);
            });
```

**Comment by teociaps** [comment] 2024-08-16 17:02
Yeah, that error occurs because the methods extend `WebApplication`, not `IApplicationBuilder`.

I'll go ahead and update them to support that interface as well.
Ty @oasaleh

**Comment by Scal-Human** [comment] 2024-08-18 08:12
@oasaleh  You found it, super.
Many thanks

**Comment by teociaps** [comment] 2024-08-19 21:48
@Scal-Human @oasaleh 
I'm back just to inform you I have added the IApplicationBuilder support on version 1.0.0 (See the [latest release](https://github.com/teociaps/SwaggerUI.Themes/releases/tag/v1.0.0))!
Please upgrade your package to check it out. :D

**Comment by Scal-Human** [comment] 2024-08-27 20:49
@teociaps Thank you, have a nice day.
